name: Generate Docs

on:
  pull_request:
    paths:
      - internal/**
      - go.mod
      - go.sum
      - main.go
      - examples/**
      - .github/workflows/generate-docs.yml

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.41.0

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: golang-${{ runner.os }}-${{ hashFiles('go.mod') }}

      - name: Run go doc
        run: go generate ./...

      - name: Commit changes
        run: |
          ghcp commit \
            -r "$GH_REPOSITORY" \
            -b "$GH_PULL_REQUEST_REF" \
            -m "chore: update Provider docs" .
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_PULL_REQUEST_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
