name: golang Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/golangci-lint.yml
      - internal/**
      - go.mod
      - go.sum
      - main.go

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: golang-${{ runner.os }}-${{ hashFiles('go.mod') }}

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Run golang test
        run: go test -v -cover ./...
