name: golang Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/golangci-lint.yml
      - internal/**
      - go.mod
      - go.sum
      - main.go

jobs:
  golang-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.41.0

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: golang-${{ runner.os }}-${{ hashFiles('go.mod') }}

      - name: Hide old comment
        run: github-comment hide -condition 'Comment.HasMeta && (Comment.Meta.SHA1 != Commit.SHA1 && Comment.Meta.JobName == "golang-test")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run golang test
        run: github-comment exec -- go test -v -cover ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
